// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

interface IERC20 {
        function transfer(address to, uint256 amount) external returns (bool);
            function transferFrom(address from, address to, uint256 amount) external returns (bool);
                function balanceOf(address account) external view returns (uint256);
}

interface IPayrollFactory {
        function registerEmployee(address employee) external;
}

contract PayrollV2 {

        // ─────────────────────────────────────────────
            // CONSTANTS
                // ─────────────────────────────────────────────

                    uint256 public constant USDC_DECIMALS = 1e6;
                        uint256 public constant MAX_RATE_AGE = 26 hours;
                            uint256 public constant MIN_PAY_PERIOD = 1 days;

                                // ─────────────────────────────────────────────
                                    // IMMUTABLES
                                        // ─────────────────────────────────────────────

                                            address public immutable settlementToken;
                                                address public immutable factory;
                                                    uint256 public immutable version;
                                                        uint256 public immutable deploymentChainId;

                                                            // ─────────────────────────────────────────────
                                                                // METADATA
                                                                    // ─────────────────────────────────────────────

                                                                        string public label;
                                                                            string public metadataURI;

                                                                                // Optional enterprise metadata
                                                                                    string public payrollCategory;
                                                                                        string public payrollBaseCurrency;

                                                                                            // ─────────────────────────────────────────────
                                                                                                // STATE
                                                                                                    // ─────────────────────────────────────────────

                                                                                                        address public owner;
                                                                                                            bool public paused;

                                                                                                                uint256 public payPeriod;
                                                                                                                    uint256 public nextPayDate;
                                                                                                                        uint256 public lastDisburseTime;

                                                                                                                            uint256 public totalDisbursed;
                                                                                                                                uint256 public totalCyclesRun;

                                                                                                                                    struct Recipient {
                                                                                                                                                bytes32 employeeId;
                                                                                                                                                        address wallet;
                                                                                                                                                                uint256 usdcAmount;
                                                                                                                                                                        string currencyCode;
                                                                                                                                                                                bool active;
                                                                                                                                                                                        uint256 addedAt;
                                                                                                                                                                                                uint256 totalReceived;
                                                                                                                                    }

                                                                                                                                        struct FxRate {
                                                                                                                                                    uint256 rate;
                                                                                                                                                            uint256 updatedAt;
                                                                                                                                                                    address updatedBy;
                                                                                                                                        }

                                                                                                                                            mapping(uint256 => Recipient) public recipients;
                                                                                                                                                uint256 public recipientCount;

                                                                                                                                                    mapping(bytes32 => FxRate) public fxRates;

                                                                                                                                                        // ─────────────────────────────────────────────
                                                                                                                                                            // EVENTS
                                                                                                                                                                // ─────────────────────────────────────────────

                                                                                                                                                                    event RecipientAdded(
                                                                                                                                                                                uint256 indexed id,
                                                                                                                                                                                        bytes32 indexed employeeId,
                                                                                                                                                                                                address indexed wallet,
                                                                                                                                                                                                        uint256 usdcAmount,
                                                                                                                                                                                                                string currencyCode
                                                                                                                                                                    );

                                                                                                                                                                        event RecipientRemoved(uint256 indexed id);

                                                                                                                                                                            event Deposited(
                                                                                                                                                                                        address indexed from,
                                                                                                                                                                                                uint256 amount,
                                                                                                                                                                                                        uint256 balance
                                                                                                                                                                            );

                                                                                                                                                                                event Disbursed(
                                                                                                                                                                                            uint256 indexed recipientId,
                                                                                                                                                                                                    address indexed wallet,
                                                                                                                                                                                                            uint256 amount
                                                                                                                                                                                );

                                                                                                                                                                                    event OwnershipTransferred(
                                                                                                                                                                                                address indexed previousOwner,
                                                                                                                                                                                                        address indexed newOwner
                                                                                                                                                                                    );

                                                                                                                                                                                        event MetadataURIUpdated(string uri);

                                                                                                                                                                                            // ─────────────────────────────────────────────
                                                                                                                                                                                                // ERRORS
                                                                                                                                                                                                    // ─────────────────────────────────────────────

                                                                                                                                                                                                        error NotOwner();
                                                                                                                                                                                                            error InvalidWallet();
                                                                                                                                                                                                                error ZeroAmount();
                                                                                                                                                                                                                    error TransferFailed();
                                                                                                                                                                                                                        error ContractPaused();
                                                                                                                                                                                                                            error InvalidRecipientId();
                                                                                                                                                                                                                                error InsufficientBalance(uint256 required, uint256 available);

                                                                                                                                                                                                                                    // ─────────────────────────────────────────────
                                                                                                                                                                                                                                        // MODIFIERS
                                                                                                                                                                                                                                            // ─────────────────────────────────────────────

                                                                                                                                                                                                                                                modifier onlyOwner() {
                                                                                                                                                                                                                                                            if (msg.sender != owner) revert NotOwner();
                                                                                                                                                                                                                                                                    _;
                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                    modifier whenNotPaused() {
                                                                                                                                                                                                                                                                if (paused) revert ContractPaused();
                                                                                                                                                                                                                                                                        _;
                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                        // ─────────────────────────────────────────────
                                                                                                                                                                                                                                                            // CONSTRUCTOR
                                                                                                                                                                                                                                                                // ─────────────────────────────────────────────

                                                                                                                                                                                                                                                                    constructor(
                                                                                                                                                                                                                                                                                address _settlementToken,
                                                                                                                                                                                                                                                                                        uint256 _payPeriodSeconds,
                                                                                                                                                                                                                                                                                                uint256 _firstPayDate,
                                                                                                                                                                                                                                                                                                        string memory _label,
                                                                                                                                                                                                                                                                                                                address _factory,
                                                                                                                                                                                                                                                                                                                        uint256 _version
                                                                                                                                                                                                                                                                    ) {
                                                                                                                                                                                                                                                                                if (_settlementToken == address(0)) revert InvalidWallet();

                                                                                                                                                                                                                                                                                        settlementToken = _settlementToken;
                                                                                                                                                                                                                                                                                                factory = _factory;
                                                                                                                                                                                                                                                                                                        version = _version;
                                                                                                                                                                                                                                                                                                                deploymentChainId = block.chainid;

                                                                                                                                                                                                                                                                                                                        owner = msg.sender;

                                                                                                                                                                                                                                                                                                                                payPeriod = _payPeriodSeconds;
                                                                                                                                                                                                                                                                                                                                        nextPayDate = _firstPayDate;
                                                                                                                                                                                                                                                                                                                                                label = _label;
                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                        // ─────────────────────────────────────────────
                                                                                                                                                                                                                                                                            // DEPOSIT
                                                                                                                                                                                                                                                                                // ─────────────────────────────────────────────

                                                                                                                                                                                                                                                                                    function deposit(uint256 amount) external whenNotPaused {

                                                                                                                                                                                                                                                                                                if (amount == 0) revert ZeroAmount();

                                                                                                                                                                                                                                                                                                        bool ok = IERC20(settlementToken).transferFrom(
                                                                                                                                                                                                                                                                                                                        msg.sender,
                                                                                                                                                                                                                                                                                                                                    address(this),
                                                                                                                                                                                                                                                                                                                                                amount
                                                                                                                                                                                                                                                                                                        );

                                                                                                                                                                                                                                                                                                                if (!ok) revert TransferFailed();

                                                                                                                                                                                                                                                                                                                        emit Deposited(
                                                                                                                                                                                                                                                                                                                                        msg.sender,
                                                                                                                                                                                                                                                                                                                                                    amount,
                                                                                                                                                                                                                                                                                                                                                                IERC20(settlementToken).balanceOf(address(this))
                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                        // ─────────────────────────────────────────────
                                                                                                                                                                                                                                                                                            // RECIPIENTS
                                                                                                                                                                                                                                                                                                // ─────────────────────────────────────────────

                                                                                                                                                                                                                                                                                                    function addRecipient(
                                                                                                                                                                                                                                                                                                                bytes32 employeeId,
                                                                                                                                                                                                                                                                                                                        address wallet,
                                                                                                                                                                                                                                                                                                                                uint256 usdcAmount,
                                                                                                                                                                                                                                                                                                                                        string calldata currencyCode
                                                                                                                                                                                                                                                                                                    ) external onlyOwner {

                                                                                                                                                                                                                                                                                                                if (wallet == address(0)) revert InvalidWallet();
                                                                                                                                                                                                                                                                                                                        if (usdcAmount == 0) revert ZeroAmount();

                                                                                                                                                                                                                                                                                                                                uint256 id = recipientCount++;

                                                                                                                                                                                                                                                                                                                                        recipients[id] = Recipient({
                                                                                                                                                                                                                                                                                                                                                        employeeId: employeeId,
                                                                                                                                                                                                                                                                                                                                                                    wallet: wallet,
                                                                                                                                                                                                                                                                                                                                                                                usdcAmount: usdcAmount,
                                                                                                                                                                                                                                                                                                                                                                                            currencyCode: currencyCode,
                                                                                                                                                                                                                                                                                                                                                                                                        active: true,
                                                                                                                                                                                                                                                                                                                                                                                                                    addedAt: block.timestamp,
                                                                                                                                                                                                                                                                                                                                                                                                                                totalReceived: 0
                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                emit RecipientAdded(
                                                                                                                                                                                                                                                                                                                                                                id,
                                                                                                                                                                                                                                                                                                                                                                            employeeId,
                                                                                                                                                                                                                                                                                                                                                                                        wallet,
                                                                                                                                                                                                                                                                                                                                                                                                    usdcAmount,
                                                                                                                                                                                                                                                                                                                                                                                                                currencyCode
                                                                                                                                                                                                                                                                                                                                                );

                                                                                                                                                                                                                                                                                                                                                        try IPayrollFactory(factory).registerEmployee(wallet) {} catch {}
                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                        function addRecipientHuman(
                                                                                                                                                                                                                                                                                                                    bytes32 employeeId,
                                                                                                                                                                                                                                                                                                                            address wallet,
                                                                                                                                                                                                                                                                                                                                    uint256 wholeUsdcAmount,
                                                                                                                                                                                                                                                                                                                                            string calldata currencyCode
                                                                                                                                                                                                                                                                                                        ) external onlyOwner {

                                                                                                                                                                                                                                                                                                                    addRecipient(
                                                                                                                                                                                                                                                                                                                                    employeeId,
                                                                                                                                                                                                                                                                                                                                                wallet,
                                                                                                                                                                                                                                                                                                                                                            wholeUsdcAmount * USDC_DECIMALS,
                                                                                                                                                                                                                                                                                                                                                                        currencyCode
                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                            function removeRecipient(uint256 id) external onlyOwner {

                                                                                                                                                                                                                                                                                                                        if (id >= recipientCount) revert InvalidRecipientId();

                                                                                                                                                                                                                                                                                                                                recipients[id].active = false;

                                                                                                                                                                                                                                                                                                                                        emit RecipientRemoved(id);
                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                // ─────────────────────────────────────────────
                                                                                                                                                                                                                                                                                                                    // DISBURSE
                                                                                                                                                                                                                                                                                                                        // ─────────────────────────────────────────────

                                                                                                                                                                                                                                                                                                                            function disburse() external whenNotPaused {

                                                                                                                                                                                                                                                                                                                                        uint256 totalRequired;

                                                                                                                                                                                                                                                                                                                                                for (uint256 i = 0; i < recipientCount; i++) {
                                                                                                                                                                                                                                                                                                                                                                if (recipients[i].active) {
                                                                                                                                                                                                                                                                                                                                                                                    totalRequired += recipients[i].usdcAmount;
                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                        uint256 balance = IERC20(settlementToken)
                                                                                                                                                                                                                                                                                                                                                                    .balanceOf(address(this));

                                                                                                                                                                                                                                                                                                                                                                            if (balance < totalRequired) {
                                                                                                                                                                                                                                                                                                                                                                                            revert InsufficientBalance(totalRequired, balance);
                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                    for (uint256 i = 0; i < recipientCount; i++) {

                                                                                                                                                                                                                                                                                                                                                                                                    Recipient storage r = recipients[i];

                                                                                                                                                                                                                                                                                                                                                                                                                if (!r.active) continue;

                                                                                                                                                                                                                                                                                                                                                                                                                            bool ok = IERC20(settlementToken)
                                                                                                                                                                                                                                                                                                                                                                                                                                            .transfer(r.wallet, r.usdcAmount);

                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (ok) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            r.totalReceived += r.usdcAmount;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            totalDisbursed += r.usdcAmount;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            emit Disbursed(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    i,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        r.wallet,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            r.usdcAmount
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                            totalCyclesRun += 1;
                                                                                                                                                                                                                                                                                                                                                                                                    lastDisburseTime = block.timestamp;
                                                                                                                                                                                                                                                                                                                                                                                                            nextPayDate += payPeriod;
                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                // ─────────────────────────────────────────────
                                                                                                                                                                                                                                                                                                                                    // METADATA
                                                                                                                                                                                                                                                                                                                                        // ─────────────────────────────────────────────

                                                                                                                                                                                                                                                                                                                                            function setMetadataURI(
                                                                                                                                                                                                                                                                                                                                                        string calldata uri
                                                                                                                                                                                                                                                                                                                                            ) external onlyOwner {

                                                                                                                                                                                                                                                                                                                                                        metadataURI = uri;

                                                                                                                                                                                                                                                                                                                                                                emit MetadataURIUpdated(uri);
                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                // ─────────────────────────────────────────────
                                                                                                                                                                                                                                                                                                                                                    // ADMIN
                                                                                                                                                                                                                                                                                                                                                        // ─────────────────────────────────────────────

                                                                                                                                                                                                                                                                                                                                                            function pause() external onlyOwner {
                                                                                                                                                                                                                                                                                                                                                                        paused = true;
                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                function unpause() external onlyOwner {
                                                                                                                                                                                                                                                                                                                                                                            paused = false;
                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                    function transferOwnership(
                                                                                                                                                                                                                                                                                                                                                                                address newOwner
                                                                                                                                                                                                                                                                                                                                                                    ) external {

                                                                                                                                                                                                                                                                                                                                                                                if (
                                                                                                                                                                                                                                                                                                                                                                                                msg.sender != owner &&
                                                                                                                                                                                                                                                                                                                                                                                                            msg.sender != factory
                                                                                                                                                                                                                                                                                                                                                                                ) revert NotOwner();

                                                                                                                                                                                                                                                                                                                                                                                        if (newOwner == address(0))
                                                                                                                                                                                                                                                                                                                                                                                                    revert InvalidWallet();

                                                                                                                                                                                                                                                                                                                                                                                                            address prev = owner;

                                                                                                                                                                                                                                                                                                                                                                                                                    owner = newOwner;

                                                                                                                                                                                                                                                                                                                                                                                                                            emit OwnershipTransferred(
                                                                                                                                                                                                                                                                                                                                                                                                                                            prev,
                                                                                                                                                                                                                                                                                                                                                                                                                                                        newOwner
                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                        // ─────────────────────────────────────────────
                                                                                                                                                                                                                                                                                                                                                                            // VIEWS
                                                                                                                                                                                                                                                                                                                                                                                // ─────────────────────────────────────────────

                                                                                                                                                                                                                                                                                                                                                                                    function contractBalance()
                                                                                                                                                                                                                                                                                                                                                                                            external
                                                                                                                                                                                                                                                                                                                                                                                                    view
                                                                                                                                                                                                                                                                                                                                                                                                            returns (uint256)
                                                                                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                                                                                            return IERC20(settlementToken)
                                                                                                                                                                                                                                                                                                                                                                                                                                        .balanceOf(address(this));
                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                    function getRecipients()
                                                                                                                                                                                                                                                                                                                                                                                                                            external
                                                                                                                                                                                                                                                                                                                                                                                                                                    view
                                                                                                                                                                                                                                                                                                                                                                                                                                            returns (Recipient[] memory)
                                                                                                                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                                                                                                                            Recipient[] memory list =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        new Recipient[](recipientCount);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                for (uint256 i = 0; i < recipientCount; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                list[i] = recipients[i];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return list;
                                                                                                                                                                                                                                                                                                                                                                                                                                                }
}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                        })
                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                }
                                                                                                                                                                                    )
                                                                                                                                                                                )
                                                                                                                                                                            )
                                                                                                                                                                    )
                                                                                                                                        }
                                                                                                                                    }
}
}
}